### ISSUE TITLE
FEATURE REQUEST: Add project tree viewer

### ISSUE THREAD

**Issue by timothymarois** [subesokun/atom-project-view#21]
Allow you to select between projects in the tree. I can not stand and stress this enough, using my keyboard to open up the project list, and then selecting one, then opening into a new window every time is the most absurd system built. 

If I had more time I'd build the damn thing myself, But seeing that you guys might have the closest thing in terms of functionality, why not tweak it if possible to allow you to quickly switch between projects and view projects within the tree itself. 

I just don't understand why this has yet to be done correctly. I have 20 different projects, and most of the time I need a file from another project, the time it takes to go into that project, and then go back to the current one is just too long. 

Hope this makes sense, most likely this isn't your direction, but for the love of coders, I want a damn project manager in the "file tree". I'm tired of typing CTRL+COMMAND+P and having 20 windows open. Its counter-intuitive.

**Comment by subesokun** [comment]
Hi @timothymarois. When I'm working on multiple projects then I add them always as root projects directly into one Atom window so that I can perform also a global project wide search. Furthermore you can use the file opener (ctrl+p ...?) to quickly open any file among those projects. Not sure if that will help you but so far this works for me and you can work solely with one window.

**Comment by subesokun** [comment]
Closing this issue for now but please feel free to leave your comments. Depending on that I'll reopen the issue.
