### ISSUE TITLE
[Nuclide] Is it suppose to get a separate tree view?

### ISSUE THREAD

**Issue by dragonxlwang** [subesokun/atom-project-view#8]
I'm getting two separate tree views, one is toggled by cmd+\ and the other is toggled by menu view -> toggle tree view. Is that the way it is supposed to be?

I've  found the problem... It seems it is so because I also use nuclide-tree-view, which override the atom's default tree view, but atom-project-view only took effects on the original tree view...

![screen shot 2015-11-14 at 5 11 43 pm](https://cloud.githubusercontent.com/assets/15812510/11166277/cd82acc6-8af2-11e5-9d7d-2a4a349bcdda.png)

**Comment by subesokun** [comment]
@dragonxlwang Oh sorry to hear that the `nuclide-tree-view` causes such issue. Actually I've tested the `project-view` and the `tree-view-git-status` package longer time ago with the Nuclide editor and everything worked fine. So I'll try to figure out if these package can be made compatible with the `nuclide-tree-view` again so that you can use it also there.

**Comment by subesokun** [comment]
Memo: Use `atom.packages.onDidActivateInitialPackages` event, see [this topic](https://discuss.atom.io/t/is-there-a-way-to-load-the-editors-default-tree-view/22710/2)

**Comment by subesokun** [comment]
@dragonxlwang As a first step to support Nuclide I've reworked the package initialization to not forcefully load any longer the tree-view. This should solve the issue that you see two tree-views but I need to provide one more update to fully support the Nuclide editor.
